### ISSUE TITLE
Labels are stationary

### ISSUE THREAD

**Issue by Airblader** [cornerman/i3-easyfocus#1]
When a window is reconfigured (resize, move), the label does not update its position.

**Comment by cornerman** [comment]
Nice idea, we could listen to [i3's window-events](http://i3wm.org/docs/ipc.html#_window_event) and trigger a redraw of all labels if the layout has changed. I hope the events are also emitted when resizing a window.

**Comment by Airblader** [comment]
Mh, why even use the IPC at all for these things? I think this tool could be made completely window manager agnostic. The IPC could still be used as an "adapter" for when the internal con id should be printed or whatever, but is there a specific reason why you didn't just query the root window's tree (for the window positions) and select ConfigureNotify for this feature?

**Comment by cornerman** [comment]
That was also my first intuition, but afaik it is not possible to get the position of the window decoration from there, which is crucial for properly positioning labels in a stacked/tabbed layout. Also I am not sure, whether it would then be possible to only iterate the visible part of the tree.

As I would also love this project to be window manager agnostic, please let me know if I am missing something. Currently, an adapter for another window manager would need to implement the methods in ipc.h.
