### ISSUE TITLE
trouble running due to libi3ipc-glib-1.0.so.0

### ISSUE THREAD

**Issue by phwelo** [cornerman/i3-easyfocus#17]
Getting the following error running i3-easyfocus:
```
$ make clean debug
Cleaning
CC src/win.c
CC src/i3-easyfocus.c
CC src/ipc.c
CC src/xcb.c
CC src/map.c
Link i3-easyfocus
```

```
$ ./i3-easyfocus
./i3-easyfocus: error while loading shared libraries: libi3ipc-glib-1.0.so.0: cannot open shared object file: No such file or directory
```

but...
```
$ locate libi3ipc-glib-1.0.so.0
/usr/local/lib/libi3ipc-glib-1.0.so.0
/usr/local/lib/libi3ipc-glib-1.0.so.0.0.0
```

is there another location that i should be linking that lib to?

**Comment by phwelo** [comment]
just for kicks and probably because i'm ignorant to how C does libraries, I tried moving that `.so.0` file to the i3-easyfocus build folder and tried running but faced the same error

**Comment by orestisfl** [comment]
`/usr/local/lib` would need to be in your `LD_LIBRARY_PATH`. See: https://stackoverflow.com/questions/4743233/is-usr-local-lib-searched-for-shared-libraries

**Comment by cornerman** [comment]
I am going to close this one, as this was answered. Feel free to reopen if there is something missing.
