### ISSUE TITLE
Floating vs tiled window focus: "cannot focus window"

### ISSUE THREAD

**Issue by mtalexan** [cornerman/i3-easyfocus#19]
If a floating window is visible and the current focus is on a tiled window when i3-easyfocus is invoked, the floating window is also labeled like the tiled windows but results in an error if selected. 

Debug output of case here: https://gist.github.com/mtalexan/ff39ee4fc1ff86d6f519a499e9f0c631 

Occurs with commit 3631d5af612d58c3d027f59c86b185590bd78ae1 (master as of now)

This appears to be an issue with jumping between tiled focus and floating focus using only i3-easyfocus.  The IPC doesn't seem to allow that.  The same issue occurs if current focus is in a floating window and you try to jump to a tiled window.

It would be great if this worked to jump between tiled and floating windows, but a temporary solution might be to identify the current mode and filter out the windows that don't match the current focus mode from labeling.  Regardless, filtering of floating vs tiled windows has to happen either for processing during focus jump or to avoid labeling windows that can't be reached.

**Comment by snippins** [comment]
@mtalexan This doesn't happen on my setup.

**Comment by cornerman** [comment]
Hmm, I can also not reproduce this problem.

What version of i3ipc-glib are you using? We had problems with overflowing ids in the currently released version 0.6 (not really sure whether this could be a problem here). Can you try with the current master of i3ipc-glib? We are also currently working on a new release for it.

**Comment by cornerman** [comment]
@mtalexan Does this still happen to you?

**Comment by mtalexan** [comment]
I just rebuilt, and it works properly now when using the latest master version of i3ipc-glib.
