### ISSUE TITLE
Add an ability to move to the previous and next tabs.

### ISSUE THREAD

**Issue by amosbird** [cornerman/i3-easyfocus#7]
This is a nice tool for jumping tabs. But there are scenarios that "Ctrl+tab/Ctrl+Shift+tab" fits better.

**Comment by cornerman** [comment]
Thanks for the input! I agree with you that switching to the previous/next tab is a nice feature, but this is out of scope for this project. It is really a generic tool for visually selecting/focusing windows and containers.

One could write a small script with i3's ipc to search for the next tabbed/stacked parent and move focus accordingly within that container. Then, it is possible to define the keybindings in your config. This is why I will close this issue. Feel free to ask if you have further questions or ideas.
