### ISSUE TITLE
Error initializing xcb after Arch xorgproto 2018.1-1 update

### ISSUE THREAD

**Issue by tuncenator** [cornerman/i3-easyfocus#9]
Upon updating the system including xorgproto 2018.1-1 which replaces [bigreqsproto, compositeproto, damageproto, dmxproto, dri2proto, dri3proto, fixesproto, fontsproto, glproto, inputproto, kbproto, presentproto, printproto, randrproto, recordproto, renderproto, resourceproto, scrnsaverproto, videoproto, xcmiscproto, xextproto, xf86dgaproto, xf86driproto, xf86miscproto, xf86vidmodeproto, xineramaproto, xproto], easyfocus no longer functions.

The package detail can be found here: https://www.archlinux.org/packages/extra/any/xorgproto/

The error received is:

```
tunc@BEER ~/.i3/easyfocus$ ./i3-easyfocus                                                                                             
error initializing xcb
```

Any ideas on how to resolve this?
Thanks

**Comment by cornerman** [comment]
Hmm, I am also on arch, but it is still working for me.

Can you manually compile with debug flag and see whether the output gives any additional information?
You can do this: `make clean debug`.

**Comment by tuncenator** [comment]
Thanks for the quick reply! That's what I got:
```
tunc@BEER ~/.i3/i3-easyfocus$ make clean debug                                                                                      master   12/02 [14:05] 
Cleaning
CC src/win.c
CC src/i3-easyfocus.c
CC src/ipc.c
CC src/xcb.c
CC src/map.c
Link i3-easyfocus
tunc@BEER ~/.i3/i3-easyfocus$ lsd                                                                                                   master   12/02 [14:06] 
total 92K
▕ drwxr-xr-x ▏tunc:users│<  sec │   4K│src
▕ -rw-r--r-- ▏tunc:users│35 sec │  35K│LICENSE
▕ -rw-r--r-- ▏tunc:users│35 sec │ 564B│Makefile
▕ -rw-r--r-- ▏tunc:users│35 sec │ 1.2K│README.md
▕ -rwxr-xr-x ▏tunc:users│<  sec │  31K│i3-easyfocus
▕ -rw-r--r-- ▏tunc:users│35 sec │  11K│screenshot.png
tunc@BEER ~/.i3/i3-easyfocus$ ./i3-easyfocus                                                                                        master   12/02 [14:06] 
[src/xcb.c:23] request failed: cannot open font. error code: 15
error initializing xcb
```

A font issue?

**Comment by cornerman** [comment]
Indeed sounds like a font issue. According to the [manpage of `xcb_open_font`](ftp://www.x.org/pub/X11R7.7/doc/man/man3/xcb_open_font.3.xhtml), it can only return a name error, which means the font was not found on the system.

The font is defined in [config.h](https://github.com/cornerman/i3-easyfocus/blob/master/src/config.h#L7). Can you check with `xlsfonts` (install xorg-xlsfonts) whether this font is available on your system?

```
xlsfonts -fn "-Misc-Fixed-Bold-R-Normal--18-120-100-100-C-90-ISO10646-1"
```

If it is not available, please try a different font. `xlsfonts` returns a list of supported fonts if no argument is provided. Please let me know, whether this helps.

**Comment by tuncenator** [comment]
Helpful indeed. Thank you very much. I don't know what happened to the other font, though still this is resolved.

Panicked a bit there as I really have gotten used to using easyfocus :smile:

**Comment by cornerman** [comment]
Great that it works again :)

**Comment by AdamSLevy** [comment]
How can I install the proper font on Arch? What font package would this be in?

**Comment by cornerman** [comment]
> How can I install the proper font on Arch? What font package would this be in?

That is a good question. It seemed like a good default at that time because it was available on all machines I tested. Maybe we need a different one?

Otherwise, you can still configure a different font in `config.h`. Or we could add an option to choose the font at runtime

**Comment by AdamSLevy** [comment]
I'm not familiar with programming applications for xorg but it seems to me that there should be a way to dynamically determine an available system font. If it were me I wouldn't consider this issue closed until you have a solution that works out of the box more robustly. 

However recompiling with a different font in config.h is not a big deal for me. Thank you

**Comment by cornerman** [comment]
@AdamSLevy There you go :)

**Comment by AdamSLevy** [comment]
Brilliant! Thank you so much!

**Comment by cornerman** [comment]
You can now set the font via argument, for example:
```
i3-easyfocus -f "-misc-fixed-medium-r-normal--20-*"
```
